In [12]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', 500)

In [5]:
df = pd.read_excel('DATA_CAP_CBS_Performace_2.xlsx')

In [8]:
df.head(2)

,AS_OF_DATE,CUST_ID,CUST_NAME,ACC_ID,BRANCH_CODE,BRANCH_DESC,PROD_TYPE,PROD_TYPE_DESC,CREDIT_LIMIT,LEDGER_BALANCE,CUST_CLASS,DATA_SOURCE,RELIGION,CORE_RELIGION,MUSLIM_DEF,ID_NO,ACC_CLASS,ISIC_NEW_FINAL_BY_OIS,ISIC_GROUP_NEW_BY_OIS,COUNT_CIF_22,COUNT_CIF_ALL,COUNT_CIF_NPF_22,COUNT_CIF_NPF_ALL,ACC_OPEN_DATE,ACC_OPEN_DATE_FOR_OD,MAIN_ACC_LINK,TDR_CIF,TDR_TIMES,SIZE_FLAG,NPF_LEGACY,CIF_CREDIT_LIMIT,FIRST_NPF_START_DATE,NEW_FINANCIAL_CIF,BRANCH_PROVINCE,DIVISION,LATE_CHARGE_DUE,COLLATERAL_REQUIRED,MAIN_OCCUPATION,EDUCATION,AGE,INCOME_LEVEL,TERM_LOAN,BILL_OLDEST_DATE,NO_OF_DPD,COMMER_COMMIT_LINK1,CCL_OPENED_DATE,CCL_CREDIT_LIMIT,NPF_FLAG,YEAR_CONTRACT,SEX,SUB_TYPE,SUB_TYPE_DESC,MARKET_CODE,MARKET_DESC,DEALER_CODE,DEALER_DESC,ISIC_NEW_FINAL,ISIC_13GROUP,ISIC_5GROUP,NEW_SIZE_FLAG,PROF_DIV_RATE,RESTRUCTURE_FLAG,LOAN_PAYMENT_HOLIDAY,BOOKED_(MM/YYYY),BOOKED_(YYYY-QQ),MOB,YOB,DQ,CODE,EVER_DQ_X,EVER_DQ_30,EVER_DQ_60,EVER_DQ_90
0,31/10/2021,750928539,ยุภาวรรณ คำทา,19042299,1,สาขาคลองตัน,7200,สินเชื่อเพื่ออุปโภค,80000,80000.00,B1,CBS,พุทธ,2_อื่นๆ,NaN,1.230300e+12,1.0,241041,22.7,1,1,0,0,19/10/2021,19/10/2021,NaN,0,NaN,1Retail,NaN,80000,NaN,NEWCIF,กรุงเทพมหานคร,1 กรุงเทพมหานครและปริมณฑล,0.0,บัญชีสินเชื่อนี้ไม่มีหลักประกัน,002-พนักงานและลูกจ้างในหน่วยงานรัฐวิสาหกิจ,03-ปริญญาตรี,34.0,"3-15,000 - 29,999",36M,30/11/2021,0,19042299,19/10/2021,80000,1_PF,2021,F,20002.0,สินเชื่อวงเงินอเนกประสงค์,1023.0,สินเชื่อสวัสดิการ,335.0,สินเชื่อสวัสดิการ MOU หน่วยงานราชการและรัฐวิสา...,241026,12.4,6.0,1-Retail/Consumer,8.0,0,0,10/2021,2021Q4,0,0,DQ_0,0,NaN,NaN,NaN,NaN
1,30/11/2021,750928539,ยุภาวรรณ คำทา,19042299,1,สาขาคลองตัน,7200,สินเชื่อเพื่ออุปโภค,80000,78048.77,B1,CBS,พุทธ,2_อื่นๆ,NaN,1.230300e+12,1.0,241041,22.7,1,1,0,0,19/10/2021,19/10/2021,NaN,0,NaN,1Retail,NaN,80000,NaN,NEWCIF,กรุงเทพมหานคร,1 กรุงเทพมหานครและปริมณฑล,0.0,บัญชีสินเชื่อนี้ไม่มีหลักประกัน,002-พนักงานและลูกจ้างในหน่วยงานรัฐวิสาหกิจ,03-ปริญญาตรี,34.0,"3-15,000 - 29,999",36M,4/1/2022,0,19042299,19/10/2021,80000,1_PF,2021,F,20002.0,สินเชื่อวงเงินอเนกประสงค์,1023.0,สินเชื่อสวัสดิการ,335.0,สินเชื่อสวัสดิการ MOU หน่วยงานราชการและรัฐวิสา...,241026,12.4,6.0,1-Retail/Consumer,8.0,0,0,10/2021,2021Q4,1,0,DQ_0,0,NaN,NaN,NaN,NaN

In [21]:
a = pd.pivot_table(df,values='ACC_ID', index='MOB',columns='EVER_DQ_X',aggfunc='count')

In [22]:
a

EVER_DQ_X  1.0
MOB
0            1
1            8
2           12
3           11
4           12
5           14
6           14
7           15
8           17
9           19
10          17
11          14
12          12
13           7
14           1